### ISSUE TITLE
Missing units needed to compile MisUtils & ConfigFrame

### ISSUE THREAD

**Issue by macmike** [t-edson/Tito-s-Terminal#1]
Hi, I've tried to compile and needed a few dependencies, UnTerminal in your other repo and

- a file called MisUtils used by Globales.
- a file called ConfigFrame used by FrameCgConex

**Comment by t-edson** [comment]
OK. These libraries are in: 
- https://github.com/t-edson/MisUtils  (used to some dialogs and translation)
- https://github.com/t-edson/ConfigFrame (used to the Configuration dialogs)

I've realized the project points to an old version of "ConfigFrame". Let me update the project, in order to compile with the new versions of the libraries.

**Comment by t-edson** [comment]
Ready. Project has been updated with the new libraries. 
If you want to have all the libraries included, you can use the file https://github.com/t-edson/Tito-s-Terminal/blob/master/Complete%20Source.rar

**Comment by macmike** [comment]
Great - thanks :) There's still 2 missing "uPreBasicos, uPreProces" used in FormPrincipal

**Comment by t-edson** [comment]
They are included in: https://github.com/t-edson/Tito-s-Terminal/blob/master/Complete%20Source.rar
You can find them too in: https://github.com/t-edson/PreSQL

**Comment by macmike** [comment]
Sorry! my mistake
